changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation and maintenance
      labels:
        - documentation
        - dependencies
        - github-actions
    - title: Other changes
      labels:
        - "*"
